// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krofkgwaegzdhygysjvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtyb2ZrZ3dhZWd6ZGh5Z3lzanZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTc0MzYsImV4cCI6MjA2NjQzMzQzNn0.GU3TnNez1qa7X32pn0azxXwWOZ-GD_e3fuhkrYaWKwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);